# Generated by Django 4.0.2 on 2022-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=30)),
                ('release_year', models.IntegerField(default=1970)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=10)),
                ('time_obtained', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('time_added', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
